### PR TITLE
Added: Possible add class in pagination list and display prev and next links

### PR DESCRIPTION
**Pull request by hugofabricio**
I made some adjustments to be able to custom class in pagination list when set and display the links previous and back.

### CODE REVIEW

**Comment by sebastiandedeyne** [comment]
Looks good, willing to merge! Could you resolve the conflicts first though (or let me know if there's something wrong on my side)? Probably just needs a rebase.

**Comment by hugofabricio** [comment]
Solved?

**Comment by sebastiandedeyne** [comment]
:+1: 

Merged and tagged as 2.2.0!

**Comment by hugofabricio** [comment]
Thanks :+1:

**Pull request merged**
